In [1]:
%matplotlib inline
import pandas as pd
import os
import os.path
import itertools
import matplotlib.pyplot as plt
import math
import pprint
import pprint as pp
import numpy as np

## 1.  LOAD DATA

In [2]:
DATA_PATH = os.path.abspath(os.path.join(os.pardir, "data/gapminder/fichiers_csv"))
DATA_PATH2 = os.path.abspath(os.path.join(os.pardir, "data"))
Child_death_FILE = "teen-fertility.csv"
GINI_FILE = "gini-complete.csv"
#Year_in_school = "Years in school men 25-34.csv""
#FERTILITY_FILE = "teen-fertility.csv"
COUNTRIES_FILE = "3-countries.csv"
#fertility_df = pd.read_csv(os.path.join(DATA_PATH, FERTILITY_FILE), sep=";")
gini_df = pd.read_csv(os.path.join(DATA_PATH, GINI_FILE),sep=",")

child_death_df = pd.read_csv(os.path.join(DATA_PATH, Child_death_FILE), sep=";",encoding = 'ISO-8859-1')
countries_df = pd.read_csv(os.path.join(DATA_PATH2, COUNTRIES_FILE), sep=";", usecols = ['Country (en)', "Continent"])
countries_df = countries_df.rename(columns ={"Country (en)" :"countries"})
path_scatter = os.path.join(os.pardir, "scatter")

In [3]:
df_intermediate = pd.merge(gini_df, child_death_df,  how='inner', on=['countries'])

In [4]:
df_intermediate.dropna(axis=0,inplace=True)

In [5]:
df_final = pd.merge(df_intermediate, countries_df,  how='left', on=['countries'])

In [7]:
df_final

       countries  Gini  Teen-fertility        Continent
0        Lesotho  63.2          71.000           Africa
1          Haiti  60.8          45.000    North America
2       Botswana  60.5          50.000           Africa
3        Namibia  59.7          70.000           Africa
4       Honduras  57.7          92.000  Central America
5         Zambia  57.5         145.000           Africa
6       Colombia  53.5          73.000    South America
7       Paraguay  53.2          71.000    South America
8      Guatemala  53.0         106.000  Central America
9          Chile  52.1          58.000    South America
10        Panama  51.9          81.000  Central America
11        Brazil  51.9          76.000    South America
12     Swaziland  50.4          81.000           Africa
13        Gambia  50.2          75.000           Africa
14      Zimbabwe  50.1          62.000           Africa
15       Ecuador  48.5          82.000    South America
16      Thailand  48.4          42.000             Asia
17        Mexico  48.3          70.000    North America
18    Madagascar  47.5         132.000           Africa
19         China  46.9           9.000             Asia
20        Rwanda  46.8          38.000           Africa
21       Bolivia  46.6          78.000    South America
22     Singapore  46.4           5.000             Asia
23      Malaysia  46.2          13.000             Asia
24   Philippines  46.0          53.000             Asia
25       Georgia  46.0          44.000             Asia
26     Argentina  45.8          67.400    South America
27    Mozambique  45.6         144.000           Africa
28       Jamaica  45.5          76.000    North America
29       Uruguay  45.3          61.000    South America
..           ...   ...             ...              ...
89       Croatia  32.0          13.000           Europe
90         Italy  31.9           7.000           Europe
91   Timor-Leste  31.9          63.000             Asia
92       Ireland  31.3          18.000           Europe
93         Egypt  30.8          45.000           Africa
94       Hungary  30.6          20.000           Europe
95    Luxembourg  30.4           9.000           Europe
96       Armenia  30.3          27.200             Asia
97     Australia  30.3          16.800        Australia
98        France  30.1           7.000           Europe
99      Pakistan  29.6          31.000             Asia
100      Austria  29.2          11.202           Europe
101      Albania  29.0          11.200           Europe
102   Kazakhstan  28.9          29.000             Asia
103  Switzerland  28.7           4.000           Europe
104      Moldova  28.5          33.000           Europe
105      Iceland  28.0          15.000           Europe
106        Malta  27.7          19.000           Europe
107      Romania  27.3          39.000           Europe
108      Germany  27.0          10.000           Europe
109       Norway  26.8           9.300           Europe
110      Finland  26.8           8.700           Europe
111      Belarus  26.5          20.794           Europe
112   Montenegro  26.2          17.000           Europe
113      Belgium  25.9          10.000           Europe
114  Netherlands  25.1           5.000           Europe
115       Sweden  24.9           6.000           Europe
116      Denmark  24.8           6.200           Europe
117      Ukraine  24.6          32.000           Europe
118     Slovenia  23.7           5.000           Europe

[119 rows x 4 columns]

In [8]:

#df_final.to_csv(path_scatter+"teen-fertility", sep=',', encoding='utf-8')
df_final.to_csv(path_scatter+'/teen-fertility.csv',sep=',', encoding='utf-8')

In [9]:
path_scatter

'../scatter'

In [10]:
DATA_PATH

'/Users/khouiyadam/Documents/IGR204 Dataviz/dataviz/data/gapminder/fichiers_csv'

In [18]:
def genrate_csv(filename):
    print (filename)
    child_death_df = pd.read_csv(os.path.join(DATA_PATH, filename), sep=";",encoding = 'ISO-8859-1')
    df_intermediate = pd.merge(gini_df, child_death_df,  how='inner', on=['countries'])
    df_intermediate.dropna(axis=0,inplace=True)
    df_final = pd.merge(df_intermediate, countries_df,  how='left', on=['countries'])
    df_final.rename(columns = {df_final.columns.tolist()[2]:'value'}, inplace=True)
    print (df_final.head(3))
    df_final.to_csv(path_scatter+'/'+filename,sep=',', encoding='utf-8')

In [19]:
path_scatter

'../scatter'

genrate_csv("Child out of school primary.csv")

In [20]:
from os import listdir
from os.path import isfile, join
onlyfiles = [f for f in listdir(DATA_PATH) if isfile(join(DATA_PATH, f))]

In [23]:
DATA_PATH

'/Users/khouiyadam/Documents/IGR204 Dataviz/dataviz/data/gapminder/fichiers_csv'

In [26]:
%%time
for file_name in onlyfiles :
    fileName, fileExtension = os.path.splitext(file_name)
    if fileExtension ==".csv" and fileName != "gini-complete":
        genrate_csv(file_name)

Child out of school primary.csv
  countries  Gini    value        Continent
0   Lesotho  63.2  98874.0           Africa
1   Namibia  59.7  52851.0           Africa
2  Honduras  57.7  45759.0  Central America
Child out of school primiary female.csv
  countries  Gini    value Continent
0   Lesotho  63.2  48464.0    Africa
1  Botswana  60.5  18042.0    Africa
2   Namibia  59.7  20909.0    Africa
Child out of school primiary male.csv
  countries  Gini    value Continent
0   Lesotho  63.2  56782.0    Africa
1  Botswana  60.5  20150.0    Africa
2   Namibia  59.7  30758.0    Africa
Child-All cause.csv
  countries  Gini      value      Continent
0   Lesotho  63.2  39.732421         Africa
1     Haiti  60.8  45.507790  North America
2  Botswana  60.5  14.952242         Africa
Child-HIV.csv
  countries  Gini      value      Continent
0   Lesotho  63.2  13.041940         Africa
1     Haiti  60.8   3.195648  North America
2  Botswana  60.5   0.000000         Africa
indicator gapminder infant_mortality.csv
  countries  Gini  value      Continent
0   Lesotho  63.2   69.2         Africa
1     Haiti  60.8   52.2  North America
2  Botswana  60.5   34.8         Africa
indicator SE_ADT_LITR_FE_ZS.csv
  countries  Gini      value        Continent
0  Botswana  60.5  85.561560           Africa
1  Honduras  57.7  84.930350  Central America
2  Colombia  53.5  93.667138    South America
indicator SE_ADT_LITR_MA_ZS.csv
  countries  Gini      value        Continent
0  Botswana  60.5  84.629920           Africa
1  Honduras  57.7  85.341228  Central America
2  Colombia  53.5  93.488251    South America
indicator SE_ADT_LITR_ZS.csv
  countries  Gini      value        Continent
0  Botswana  60.5  85.090850           Africa
1  Honduras  57.7  85.123311  Central America
2  Colombia  53.5  93.580534    South America
indicator SE_ENR_PRSC_FM_ZS.csv
  countries  Gini    value        Continent
0   Lesotho  63.2  106.064           Africa
1  Honduras  57.7  107.178  Central America
2  Colombia  53.5  103.712    South America
indicator SP_ADO_TFRT.csv
  countries  Gini    value      Continent
0   Lesotho  63.2  65.8524         Africa
1     Haiti  60.8  43.3088  North America
2  Botswana  60.5  47.1324         Africa
indicator wdi urbanpopulation.csv
  countries  Gini    value      Continent
0   Lesotho  63.2  27.5738         Africa
1     Haiti  60.8  53.3126  North America
2  Botswana  60.5  61.6148         Africa
Indicator_estimated new births.csv
  countries  Gini     value      Continent
0   Lesotho  63.2   60718.0         Africa
1     Haiti  60.8  263263.0  North America
2  Botswana  60.5   55461.0         Africa
Indicator_Poverty headcount ratio at $2 a day (PPP) (% of population).csv
  countries  Gini  value        Continent
0  Honduras  57.7  32.61  Central America
1  Colombia  53.5  20.89    South America
2  Paraguay  53.2  13.56    South America
indicatorpolityiv.csv
  countries  Gini  value      Continent
0   Lesotho  63.2    4.0         Africa
1     Haiti  60.8   -2.0  North America
2  Botswana  60.5    8.0         Africa
roads paved.csv
  countries  Gini      value        Continent
0   Lesotho  63.2  18.299999           Africa
1     Haiti  60.8  24.299999    North America
2  Honduras  57.7  20.400000  Central America
suicide indicator age adjusted -05 extrapolated UL 2020100818b.csv
  countries  Gini      value      Continent
0   Lesotho  63.2   7.858619         Africa
1     Haiti  60.8   1.519248  North America
2  Botswana  60.5  11.213970         Africa
teen-fertility.csv
  countries  Gini  value      Continent
0   Lesotho  63.2   71.0         Africa
1     Haiti  60.8   45.0  North America
2  Botswana  60.5   50.0         Africa
CPU times: user 206 ms, sys: 35.2 ms, total: 241 ms
Wall time: 239 ms